# Generated by Django 4.2.4 on 2023-09-07 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentconsultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_start_date', models.DateField(auto_now_add=True)),
                ('appointment_status', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('times_slot', models.CharField(max_length=255)),
                ('clinicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediline.clinic')),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediline.doctors')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
