# Generated by Django 4.2.4 on 2023-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='userid',
            field=models.UUIDField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
