# Generated by Django 4.2.4 on 2023-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0002_appointmentconsultations_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentconsultations',
            name='patient_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
