# Generated by Django 4.2.4 on 2023-08-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0003_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='userid',
        ),
    ]
