# Generated by Django 4.2.4 on 2023-08-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0005_rename_user_id_files_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('professional_details', models.CharField(max_length=1000)),
                ('practicing_from', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=255)),
                ('institute_name', models.CharField(max_length=255)),
                ('procurement_year', models.TimeField()),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediline.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediline.doctors')),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediline.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=100)),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediline.doctors')),
            ],
        ),
    ]
