# Generated by Django 4.2.4 on 2023-08-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0006_doctors_specialization_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctors',
            table='mediline_doctors',
        ),
    ]
