# Generated by Django 4.2.4 on 2023-08-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0007_alter_doctors_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
