# Generated by Django 4.2.4 on 2023-08-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0008_alter_doctors_date_joined'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctors',
            table='doctors',
        ),
    ]
