# Generated by Django 4.2.4 on 2023-08-27 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0009_alter_doctors_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(max_length=255)),
                ('appointment_start_date', models.DateField(auto_now_add=True)),
                ('appointment_status', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('clinicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediline.clinic')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
