# Generated by Django 4.2.4 on 2023-08-29 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0010_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=100)),
                ('morning_slot', models.CharField(blank=True, max_length=100, null=True)),
                ('evening_slot', models.CharField(blank=True, max_length=100, null=True)),
                ('is_available', models.BooleanField()),
                ('clinicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediline.clinic')),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediline.doctors')),
            ],
        ),
    ]
