# Generated by Django 4.2.4 on 2023-08-30 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0011_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerid', models.CharField(max_length=500)),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('patient_name', models.CharField(max_length=255)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
