# Generated by Django 4.2.4 on 2023-09-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediline', '0012_testappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
